/**
 * Russian posture: the overseas footprint, the strategic-forces bases inside
 * Russia that drive events elsewhere, and the facilities on territory whose
 * sovereignty is contested.
 *
 * Tartus is the reason every popup on this layer carries a source and a date.
 * The probed Wikidata rows returned it twice — once under the Russian Navy and
 * once under the Soviet Navy — and again under both Syria and, via a stray
 * Balaklava entry, Russia and Ukraine. The facility's actual status has been
 * unsettled since the Assad government fell in December 2024, so it is carried
 * at confidence "reported" and says so.
 */
import type { MilitaryBase } from "./military-bases.ts";

const V = "2026-09-20";
const OSINT = "Open-source reporting and satellite imagery analysis";
const OSINT_URL = "https://www.iiss.org/publications/the-military-balance/";
const MOD = "Russian Ministry of Defence statements";
const MOD_URL = "https://eng.mil.ru/";

export const RUS_BASES: MilitaryBase[] = [
  // ---- Overseas
  {
    id: "tartus",
    name: "Tartus naval facility",
    short: "Tartus",
    lat: 34.91,
    lon: 35.87,
    operator: "RUS",
    hostCountry: "SYR",
    branch: "naval",
    status: "reported",
    confidence: "reported",
    role: "Russia's only Mediterranean naval repair and replenishment point, held since 1971 and expanded under a 49-year lease signed in 2017. Status unsettled since December 2024: Russian vessels were reported withdrawn and equipment shipped out, while Moscow has sought to renegotiate access with the successor government.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "Whether the 2017 lease binds the post-Assad Syrian government is disputed and unresolved.",
  },
  {
    id: "khmeimim",
    name: "Khmeimim Air Base",
    short: "Khmeimim",
    lat: 35.4011,
    lon: 35.9486,
    operator: "RUS",
    hostCountry: "SYR",
    branch: "air",
    status: "reported",
    confidence: "reported",
    role: "The air base that made the 2015 Russian intervention possible and the logistics bridge to Libya and the Sahel. Reported drawdown from December 2024 with a residual presence retained pending negotiation.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "Same unresolved question as Tartus.",
  },
  {
    id: "gyumri",
    name: "102nd Military Base, Gyumri",
    short: "Gyumri",
    lat: 40.79,
    lon: 43.85,
    operator: "RUS",
    hostCountry: "ARM",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "Russia's forward garrison in the South Caucasus, leased to 2044. Its failure to act during the 2020 and 2023 Karabakh campaigns is why Armenia has frozen its CSTO participation.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "erebuni",
    name: "Erebuni Air Base (3624th)",
    short: "Erebuni",
    lat: 40.12,
    lon: 44.465,
    operator: "RUS",
    hostCountry: "ARM",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Russian MiG-29s and helicopters sharing Yerevan's second airport — the air component of the Gyumri garrison.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "kant",
    name: "Kant Air Base",
    short: "Kant",
    lat: 42.8531,
    lon: 74.8464,
    operator: "RUS",
    hostCountry: "KGZ",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The CSTO's designated air component in Central Asia, established in 2003 partly as an answer to the then-US presence at Manas 20 km away.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "dushanbe-201",
    name: "201st Military Base, Dushanbe / Gissar",
    short: "201st Base",
    lat: 38.56,
    lon: 68.78,
    operator: "RUS",
    hostCountry: "TJK",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "Russia's largest garrison outside its own territory, on the Afghan border, leased to 2042. The CSTO's southern tripwire.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "baranovichi",
    name: "Volga early-warning radar, Baranovichi",
    short: "Baranovichi",
    lat: 52.85,
    lon: 26.47,
    operator: "RUS",
    hostCountry: "BLR",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "A Russian-operated missile early-warning radar on Belarusian soil covering western Europe and the North Atlantic, on a rent-free 25-year lease. Russia's strategic warning has a hole in it without this site.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "vileyka",
    name: "43rd Naval Communications Centre, Vileyka",
    short: "Vileyka",
    lat: 54.46,
    lon: 26.78,
    operator: "RUS",
    hostCountry: "BLR",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "Very-low-frequency transmitter for communicating with submerged ballistic-missile submarines in the Atlantic — a nuclear command-and-control node outside Russia.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "ochamchire",
    name: "Ochamchire naval facility",
    short: "Ochamchire",
    lat: 42.71,
    lon: 41.46,
    operator: "RUS",
    hostCountry: "GEO",
    branch: "naval",
    status: "under-construction",
    confidence: "reported",
    role: "Announced in October 2023 as a Black Sea Fleet base in Abkhazia — a direct response to Ukrainian strikes on Sevastopol, putting warships 500 km further from Ukrainian missiles.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "In Abkhazia, recognised as Georgian territory by almost every state and as independent by Russia and a handful of others. Georgia calls the facility illegal.",
  },
  {
    id: "gudauta",
    name: "Bombora airfield, Gudauta",
    short: "Gudauta",
    lat: 43.1,
    lon: 40.58,
    operator: "RUS",
    hostCountry: "GEO",
    branch: "air",
    status: "reported",
    confidence: "reported",
    role: "Russia's 7th Military Base in Abkhazia, retained after the 1999 CFE commitment to close it and expanded after 2008.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "In Abkhazia; see Ochamchire.",
  },
  {
    id: "tskhinvali",
    name: "4th Guards Military Base, Tskhinvali",
    short: "Tskhinvali",
    lat: 42.22,
    lon: 43.97,
    operator: "RUS",
    hostCountry: "GEO",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "The Russian garrison in South Ossetia, 25 km from Georgia's main east-west highway and 100 km from Tbilisi.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
    hostNote: "In South Ossetia, recognised as Georgian territory by almost every state.",
  },
  {
    id: "sevastopol",
    name: "Sevastopol naval base",
    short: "Sevastopol",
    lat: 44.6167,
    lon: 33.525,
    operator: "RUS",
    hostCountry: "UKR",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Historic Black Sea Fleet headquarters. Sustained Ukrainian missile and uncrewed-surface-vessel attacks from 2022 forced most of the surviving fleet east to Novorossiysk — the first time in modern history a navy has been driven from its main base by a state with no navy of its own.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "In Crimea, internationally recognised as Ukraine and under Russian occupation since 2014. Russia administers it as its own territory.",
  },

  // ---- Strategic forces inside Russia
  {
    id: "novorossiysk",
    name: "Novorossiysk naval base",
    short: "Novorossiysk",
    lat: 44.7167,
    lon: 37.7833,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "The Black Sea Fleet's fallback after Sevastopol became untenable, with a submarine basin built out from 2020. Also struck by Ukrainian USVs, which is the point: there is no safe Black Sea port left.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "baltiysk",
    name: "Baltiysk naval base",
    short: "Baltiysk",
    lat: 54.65,
    lon: 19.9,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Baltic Fleet headquarters in Kaliningrad — Russia's only ice-free Baltic port, now enclosed by NATO members on every side since Finland and Sweden acceded.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "chernyakhovsk",
    name: "Chernyakhovsk missile garrison",
    short: "Chernyakhovsk",
    lat: 54.6333,
    lon: 21.8167,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "Iskander-M brigade in Kaliningrad, inside range of Warsaw, Vilnius and Berlin — the reason the Suwałki gap is a planning problem rather than a map feature.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "severomorsk",
    name: "Severomorsk naval base",
    short: "Severomorsk",
    lat: 69.07,
    lon: 33.42,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Northern Fleet headquarters and the gateway to the GIUK gap — the fleet that matters most to NATO and the one least touched by the Ukraine war.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "gadzhiyevo",
    name: "Gadzhiyevo submarine base",
    short: "Gadzhiyevo",
    lat: 69.25,
    lon: 33.33,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Main basing for the Northern Fleet's Borei-class ballistic-missile submarines — roughly half of Russia's survivable nuclear deterrent.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "rybachiy",
    name: "Rybachiy submarine base, Vilyuchinsk",
    short: "Rybachiy",
    lat: 52.92,
    lon: 158.48,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "The Pacific Fleet's ballistic-missile submarine base on Kamchatka, with direct deep-water access to the open Pacific.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "fokino",
    name: "Pacific Fleet HQ, Vladivostok / Fokino",
    short: "Vladivostok",
    lat: 43.115,
    lon: 131.885,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Pacific Fleet headquarters and surface-force base, and the port from which Russian and Chinese navies have run joint patrols around Japan since 2021.",
    source: MOD,
    sourceUrl: MOD_URL,
    lastVerified: V,
  },
  {
    id: "engels-2",
    name: "Engels-2 Air Base",
    short: "Engels-2",
    lat: 51.475,
    lon: 46.21,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Main Tu-95MS and Tu-160 strategic bomber base and a launch point for cruise-missile strikes on Ukraine. Hit by Ukrainian long-range drones from December 2022 onward, 600 km inside Russia.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "olenya",
    name: "Olenya Air Base",
    short: "Olenya",
    lat: 68.1517,
    lon: 33.4633,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Arctic strategic-bomber dispersal field used for strikes on Ukraine specifically because of its distance from it — and struck anyway in the June 2025 Ukrainian drone operation, 1,800 km from the border.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "nagurskoye",
    name: "Nagurskoye (Arctic Trefoil)",
    short: "Nagurskoye",
    lat: 80.803,
    lon: 47.66,
    operator: "RUS",
    hostCountry: "RUS",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The northernmost military airfield on earth, on Franz Josef Land — the hard edge of Russia's claim to regulate the Northern Sea Route.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
];
