/**
 * Chinese posture, and the host-nation sites that carry strategic weight in
 * their own right.
 *
 * China's entry deserves care: it has exactly one acknowledged overseas base,
 * and a set of facilities that are variously reported, suspected or denied. Those
 * are carried at confidence "reported" and say what the operator claims, because
 * the gap between a base and a port a Chinese firm operates is the whole
 * analytical question here and collapsing it would be the error.
 *
 * The South China Sea reef airfields are listed with the host set to China
 * because that is who built and occupies them, with a host note recording that
 * the features are claimed by others and that the 2016 arbitral tribunal found
 * against the claim they rest on.
 */
import type { MilitaryBase } from "./military-bases.ts";

const V = "2026-09-20";
const AMTI = "CSIS Asia Maritime Transparency Initiative";
const AMTI_URL = "https://amti.csis.org/";
const OSINT = "Open-source reporting and satellite imagery analysis";
const OSINT_URL = "https://www.iiss.org/publications/the-military-balance/";

export const OTHER_BASES: MilitaryBase[] = [
  // ---- China
  {
    id: "djibouti-plan",
    name: "PLA Support Base Djibouti",
    short: "PLA Djibouti",
    lat: 11.59,
    lon: 43.065,
    operator: "CHN",
    hostCountry: "DJI",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "China's only acknowledged overseas military base, opened 2017, with a pier long enough for its largest surface ships. Four kilometres from Camp Lemonnier, which makes Djibouti the only country hosting both.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "yulin",
    name: "Yulin Naval Base, Sanya",
    short: "Yulin",
    lat: 18.22,
    lon: 109.69,
    operator: "CHN",
    hostCountry: "CHN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "The PLAN's ballistic-missile submarine base on Hainan, with underground pens giving direct submerged access to the deep South China Sea. The reason China wants that sea treated as its own.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "fiery-cross",
    name: "Fiery Cross Reef (Yongshu Jiao)",
    short: "Fiery Cross",
    lat: 9.55,
    lon: 112.89,
    operator: "CHN",
    hostCountry: "CHN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "A 3,000 m runway, radar suite, hangars and missile shelters built on a reef that was underwater at high tide in 2014. The southernmost Chinese airfield and the anchor of the Spratly position.",
    source: AMTI,
    sourceUrl: AMTI_URL,
    lastVerified: V,
    hostNote: "Claimed by the Philippines, Vietnam and Taiwan. The 2016 UNCLOS arbitral tribunal found China's nine-dash-line claim had no legal basis; China rejects the ruling.",
  },
  {
    id: "subi-reef",
    name: "Subi Reef (Zhubi Jiao)",
    short: "Subi Reef",
    lat: 10.92,
    lon: 114.08,
    operator: "CHN",
    hostCountry: "CHN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The second of the three big Spratly airbases, 25 km from Philippine-held Thitu Island, with the largest hangar and shelter complement of the group.",
    source: AMTI,
    sourceUrl: AMTI_URL,
    lastVerified: V,
    hostNote: "Claimed by the Philippines, Vietnam and Taiwan; see Fiery Cross.",
  },
  {
    id: "mischief-reef",
    name: "Mischief Reef (Meiji Jiao)",
    short: "Mischief Reef",
    lat: 9.9,
    lon: 115.53,
    operator: "CHN",
    hostCountry: "CHN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The third Spratly airbase, and the one the 2016 tribunal specifically found to lie inside the Philippine exclusive economic zone.",
    source: AMTI,
    sourceUrl: AMTI_URL,
    lastVerified: V,
    hostNote: "Found by the 2016 arbitral tribunal to be within the Philippine EEZ. Occupied by China since 1995.",
  },
  {
    id: "woody-island",
    name: "Woody Island (Yongxing Dao)",
    short: "Woody Island",
    lat: 16.83,
    lon: 112.34,
    operator: "CHN",
    hostCountry: "CHN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The administrative and military centre of the Paracels, with fighters, HQ-9 surface-to-air missiles and anti-ship missiles deployed since 2016.",
    source: AMTI,
    sourceUrl: AMTI_URL,
    lastVerified: V,
    hostNote: "Claimed by Vietnam and Taiwan. Seized from South Vietnam in 1974.",
  },
  {
    id: "ream",
    name: "Ream Naval Base",
    short: "Ream",
    lat: 10.51,
    lon: 103.61,
    operator: "CHN",
    hostCountry: "KHM",
    branch: "naval",
    status: "reported",
    confidence: "reported",
    role: "Chinese-funded reconstruction with a pier sized for vessels far larger than anything Cambodia operates, and two Chinese warships berthed near-continuously since December 2023. Phnom Penh denies any exclusive Chinese access; its constitution forbids foreign bases.",
    source: AMTI,
    sourceUrl: AMTI_URL,
    lastVerified: V,
    hostNote: "Cambodia denies this is a Chinese base. Listed as reported, not acknowledged.",
  },
  {
    id: "gwadar",
    name: "Gwadar port",
    short: "Gwadar",
    lat: 25.13,
    lon: 62.33,
    operator: "CHN",
    hostCountry: "PAK",
    branch: "naval",
    status: "reported",
    confidence: "reported",
    role: "A Chinese-operated commercial port under a 40-year concession, 400 km from the Strait of Hormuz, long forecast as a PLAN base. No Chinese military facility has been confirmed there and both governments deny one is planned.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "Commercial concession, not an acknowledged military base. Included because the forecast drives analysis, and marked reported so it cannot be read as established.",
  },
  {
    id: "gnq-bata",
    name: "Bata port (reported Atlantic access)",
    short: "Bata",
    lat: 1.85,
    lon: 9.77,
    operator: "CHN",
    hostCountry: "GNQ",
    branch: "naval",
    status: "reported",
    confidence: "reported",
    role: "Named repeatedly since 2021 by US officials as China's preferred site for its first Atlantic naval base. No facility exists; the entry records a stated intelligence assessment, not an installation.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
    hostNote: "No confirmed Chinese military presence. Carried as a reported assessment only.",
  },

  // ---- Host-nation sites that matter strategically
  {
    id: "orland",
    name: "Ørland Main Air Station",
    short: "Ørland",
    lat: 63.7,
    lon: 9.604,
    operator: "NOR",
    hostCountry: "NOR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Norway's F-35 main operating base and NATO's northern quick-reaction alert — the alliance's primary sensor on Russian Northern Fleet air activity.",
    source: "Norwegian Armed Forces",
    sourceUrl: "https://www.forsvaret.no/en",
    lastVerified: V,
  },
  {
    id: "evenes",
    name: "Evenes Air Station",
    short: "Evenes",
    lat: 68.49,
    lon: 16.68,
    operator: "NOR",
    hostCountry: "NOR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Forward F-35 QRA base and P-8 maritime patrol field inside the Arctic Circle, 300 km from the Kola submarine bastion.",
    source: "Norwegian Armed Forces",
    sourceUrl: "https://www.forsvaret.no/en",
    lastVerified: V,
  },
  {
    id: "nevatim",
    name: "Nevatim Air Base",
    short: "Nevatim",
    lat: 31.23,
    lon: 34.66,
    operator: "ISR",
    hostCountry: "ISR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Israel's F-35 base and strategic transport hub, and the declared target of the Iranian ballistic-missile salvos of April and October 2024 — the first state-on-state missile attacks on Israeli soil.",
    source: "Israel Defense Forces",
    sourceUrl: "https://www.idf.il/en/",
    lastVerified: V,
  },
  {
    id: "haifa-naval",
    name: "Haifa naval base",
    short: "Haifa",
    lat: 32.83,
    lon: 35.0,
    operator: "ISR",
    hostCountry: "ISR",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Home of Israel's Dolphin-class submarines, widely assessed as its sea-based second-strike capability, and of the corvettes guarding the offshore gas fields.",
    source: "Israel Defense Forces",
    sourceUrl: "https://www.idf.il/en/",
    lastVerified: V,
  },
  {
    id: "palmachim",
    name: "Palmachim Air Base",
    short: "Palmachim",
    lat: 31.897,
    lon: 34.69,
    operator: "ISR",
    hostCountry: "ISR",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "Israel's satellite launch site and UAV base — the only orbital launch facility in the Middle East, and the one that launches westward over the sea for political rather than physical reasons.",
    source: "Israel Defense Forces",
    sourceUrl: "https://www.idf.il/en/",
    lastVerified: V,
  },
  {
    id: "bandar-abbas",
    name: "Bandar Abbas naval base",
    short: "Bandar Abbas",
    lat: 27.15,
    lon: 56.21,
    operator: "IRN",
    hostCountry: "IRN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Headquarters of both the regular Iranian navy's southern fleet and the IRGC Navy fast-attack force — the base from which the Strait of Hormuz is actually controlled.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "chabahar",
    name: "Chabahar naval base",
    short: "Chabahar",
    lat: 25.29,
    lon: 60.62,
    operator: "IRN",
    hostCountry: "IRN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Iran's only port outside the Persian Gulf, which is why it is the designated fallback if Hormuz is closed — including by Iran itself. Also India's route to Afghanistan and Central Asia bypassing Pakistan.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "sohae",
    name: "Sohae Satellite Launching Station",
    short: "Sohae",
    lat: 39.66,
    lon: 124.705,
    operator: "PRK",
    hostCountry: "PRK",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "North Korea's space launch site and the test stand for the engines of its intercontinental ballistic missiles, expanded continuously since the 2018 promise to dismantle it.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "sinpo",
    name: "Sinpo South Shipyard",
    short: "Sinpo",
    lat: 39.93,
    lon: 127.6,
    operator: "PRK",
    hostCountry: "PRK",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Where North Korea builds and tests its ballistic-missile submarines — the programme that would make its deterrent survivable.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "yonaguni",
    name: "JGSDF Camp Yonaguni",
    short: "Yonaguni",
    lat: 24.467,
    lon: 123.01,
    operator: "JPN",
    hostCountry: "JPN",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "Japanese territory 110 km from Taiwan, with a coastal surveillance unit and a planned missile deployment. The closest any US treaty ally comes to the strait.",
    source: "Japan Ministry of Defense",
    sourceUrl: "https://www.mod.go.jp/en/",
    lastVerified: V,
  },
  {
    id: "ishigaki",
    name: "JGSDF Camp Ishigaki",
    short: "Ishigaki",
    lat: 24.38,
    lon: 124.18,
    operator: "JPN",
    hostCountry: "JPN",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "Opened 2023 with Type 12 anti-ship and Type 03 surface-to-air missiles — the southwestern islands' conversion from empty flank to defended line.",
    source: "Japan Ministry of Defense",
    sourceUrl: "https://www.mod.go.jp/en/",
    lastVerified: V,
  },
  {
    id: "zuoying",
    name: "Zuoying Naval Base, Kaohsiung",
    short: "Zuoying",
    lat: 22.61,
    lon: 120.26,
    operator: "TWN",
    hostCountry: "TWN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Taiwan's main naval base and fleet headquarters, on the island's sheltered western coast, and where its indigenous submarine programme is based.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "chiashan",
    name: "Chiashan Air Base, Hualien",
    short: "Chiashan",
    lat: 23.975,
    lon: 121.61,
    operator: "TWN",
    hostCountry: "TWN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Hardened shelters tunnelled into the mountains on the east coast, designed to keep Taiwanese fighters alive through an opening missile salvo from the mainland.",
    source: OSINT,
    sourceUrl: OSINT_URL,
    lastVerified: V,
  },
  {
    id: "karwar",
    name: "INS Kadamba, Karwar (Project Seabird)",
    short: "Karwar",
    lat: 14.8,
    lon: 74.13,
    operator: "IND",
    hostCountry: "IND",
    branch: "naval",
    status: "under-construction",
    confidence: "documented",
    role: "India's purpose-built west-coast base, being expanded to berth its carriers and nuclear submarines away from the congestion of Mumbai and the reach of Pakistan.",
    source: "Indian Ministry of Defence",
    sourceUrl: "https://www.mod.gov.in/",
    lastVerified: V,
  },
  {
    id: "port-blair",
    name: "Andaman & Nicobar Command, Port Blair",
    short: "Port Blair",
    lat: 11.644,
    lon: 92.73,
    operator: "IND",
    hostCountry: "IND",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "India's only unified tri-service command, sitting on the western approach to the Strait of Malacca — the position from which Chinese energy imports could in principle be interdicted.",
    source: "Indian Ministry of Defence",
    sourceUrl: "https://www.mod.gov.in/",
    lastVerified: V,
  },
  {
    id: "changi",
    name: "Changi Naval Base",
    short: "Changi",
    lat: 1.32,
    lon: 103.99,
    operator: "SGP",
    hostCountry: "SGP",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Singapore's own base, with a berth built to take a US aircraft carrier and a standing US logistics presence under a 1990 memorandum. Access without basing, at the Malacca and Singapore Strait exit.",
    source: "Singapore Ministry of Defence",
    sourceUrl: "https://www.mindef.gov.sg/",
    lastVerified: V,
  },
  {
    id: "french-djibouti",
    name: "French Forces in Djibouti (BA 188)",
    short: "FFDj",
    lat: 11.568,
    lon: 43.148,
    operator: "FRA",
    hostCountry: "DJI",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "France's largest permanent overseas garrison, held continuously since independence in 1977 and now the last substantial French base in Africa after the Sahel withdrawals.",
    source: "French Ministry of the Armed Forces",
    sourceUrl: "https://www.defense.gouv.fr/",
    lastVerified: V,
  },
  {
    id: "ndjamena",
    name: "Base aérienne projetée, N'Djamena",
    short: "N'Djamena",
    lat: 12.1337,
    lon: 15.034,
    operator: "FRA",
    hostCountry: "TCD",
    branch: "air",
    status: "closed",
    confidence: "documented",
    role: "The last French air base in the Sahel and the old headquarters of Operation Barkhane. Chad ended the defence cooperation agreement in November 2024 and the French withdrawal completed in January 2025, closing out a presence that had run since 1986.",
    source: "French Ministry of the Armed Forces",
    sourceUrl: "https://www.defense.gouv.fr/",
    lastVerified: V,
  },
  {
    id: "niamey",
    name: "Base aérienne 101, Niamey",
    short: "Niamey",
    lat: 13.4815,
    lon: 2.1836,
    operator: "FRA",
    hostCountry: "NER",
    branch: "air",
    status: "closed",
    confidence: "documented",
    role: "France's Sahel drone and fighter base after the 2022 withdrawal from Mali. Ordered out after the July 2023 coup; withdrawal completed December 2023, nine months before the United States left Agadez.",
    source: "French Ministry of the Armed Forces",
    sourceUrl: "https://www.defense.gouv.fr/",
    lastVerified: V,
  },
];
