/**
 * United States overseas posture, and the two allied sovereign-base sets that
 * only make sense alongside it.
 *
 * Selection rule: an installation earns a place if removing it would change what
 * the United States can do in a theatre. Ramstein, Al Udeid, Yokosuka, Guam,
 * Diego Garcia and Pituffik are here for that reason; the several hundred
 * barracks, depots and training areas that make up the rest of the footprint are
 * not, because a roster of 750 dots says less than a roster of 75.
 */
import type { MilitaryBase } from "./military-bases.ts";

const V = "2026-09-20";
const EUCOM = "US European Command / USAFE posture statements";
const EUCOM_URL = "https://www.eucom.mil/";
const INDOPACOM = "US Indo-Pacific Command posture statements";
const INDOPACOM_URL = "https://www.pacom.mil/";
const CENTCOM = "US Central Command posture statements";
const CENTCOM_URL = "https://www.centcom.mil/";
const BSR = "DoD Base Structure Report / service fact sheets";
const BSR_URL = "https://www.defense.gov/";

export const US_BASES: MilitaryBase[] = [
  // ---- Europe
  {
    id: "ramstein",
    name: "Ramstein Air Base",
    short: "Ramstein",
    lat: 49.4369,
    lon: 7.6003,
    operator: "USA",
    hostCountry: "DEU",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "HQ US Air Forces in Europe and NATO Allied Air Command; the air-mobility gate for everything the US moves into Europe, the Middle East and Africa, and the venue for the Ukraine Defense Contact Group.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "spangdahlem",
    name: "Spangdahlem Air Base",
    short: "Spangdahlem",
    lat: 49.9727,
    lon: 6.6925,
    operator: "USA",
    hostCountry: "DEU",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "52nd Fighter Wing — the only US F-16 wing left in northern Europe and the support wing for the NATO nuclear mission.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "stuttgart",
    name: "Patch Barracks, Stuttgart",
    short: "Stuttgart",
    lat: 48.7419,
    lon: 9.0908,
    operator: "USA",
    hostCountry: "DEU",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "HQ US European Command, with US Africa Command at Kelley Barracks in the same city. Two combatant commands on one host nation's soil.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "grafenwoehr",
    name: "Grafenwöhr Training Area (USAG Bavaria)",
    short: "Grafenwöhr",
    lat: 49.6983,
    lon: 11.9403,
    operator: "USA",
    hostCountry: "DEU",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "The largest US training range outside the continental United States and where Ukrainian crews were trained on Abrams, Patriot and Bradley.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "aviano",
    name: "Aviano Air Base",
    short: "Aviano",
    lat: 46.0319,
    lon: 12.5965,
    operator: "USA",
    hostCountry: "ITA",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "31st Fighter Wing. Widely reported as one of six European sites storing US B61 gravity bombs for the NATO nuclear sharing mission; neither Washington nor Rome confirms the storage.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "naples",
    name: "Naval Support Activity Naples",
    short: "Naples",
    lat: 40.885,
    lon: 14.29,
    operator: "USA",
    hostCountry: "ITA",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "HQ US Sixth Fleet and US Naval Forces Europe-Africa — the command that runs every US warship in the Mediterranean, Black Sea approaches and eastern Atlantic.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "sigonella",
    name: "Naval Air Station Sigonella",
    short: "Sigonella",
    lat: 37.4017,
    lon: 14.9224,
    operator: "USA",
    hostCountry: "ITA",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "P-8 Poseidon and MQ-4C Triton operating hub for the central Mediterranean and North Africa; the closest US ISR base to Libya.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "rota",
    name: "Naval Station Rota",
    short: "Rota",
    lat: 36.645,
    lon: -6.3494,
    operator: "USA",
    hostCountry: "ESP",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Forward-deployed Aegis ballistic-missile-defence destroyers — the sea-based half of NATO's missile shield — 40 km from the Strait of Gibraltar.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "lakenheath",
    name: "RAF Lakenheath",
    short: "Lakenheath",
    lat: 52.4093,
    lon: 0.561,
    operator: "USA",
    hostCountry: "GBR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "48th Fighter Wing, the only US F-35A wing in Europe. US budget documents from 2022 onward reinstated Lakenheath on a list of nuclear-mission support sites, which is reported but not confirmed.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "fairford",
    name: "RAF Fairford",
    short: "Fairford",
    lat: 51.6822,
    lon: -1.79,
    operator: "USA",
    hostCountry: "GBR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The US bomber forward operating location in Europe — B-52, B-1 and B-2 deployments, and the runway that puts strategic bombers within unrefuelled reach of the Baltic.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "menwith-hill",
    name: "RAF Menwith Hill",
    short: "Menwith Hill",
    lat: 54.0089,
    lon: -1.69,
    operator: "USA",
    hostCountry: "GBR",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "The largest US signals-intelligence and satellite ground station outside the United States, and a node in the ballistic-missile early-warning chain.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "pituffik",
    name: "Pituffik Space Base (Thule)",
    short: "Pituffik",
    lat: 76.5312,
    lon: -68.7032,
    operator: "USA",
    hostCountry: "DNK",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "The northernmost US installation anywhere: upgraded early-warning radar and space surveillance covering the polar approach, plus the only deep-water port in northern Greenland.",
    source: "US Space Force installation fact sheets",
    sourceUrl: "https://www.spaceforce.mil/",
    lastVerified: V,
    hostNote: "On Greenland, a self-governing part of the Kingdom of Denmark; governed by the 1951 US-Denmark defence agreement as revised in 2004.",
  },
  {
    id: "deveselu",
    name: "Naval Support Facility Deveselu (Aegis Ashore)",
    short: "Deveselu",
    lat: 44.0703,
    lon: 24.4048,
    operator: "USA",
    hostCountry: "ROU",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "The first land-based Aegis interceptor site in Europe, operational since 2016. Russia asserts its Mk 41 launchers breach the now-defunct INF Treaty; the United States denies it.",
    source: "US Missile Defense Agency",
    sourceUrl: "https://www.mda.mil/",
    lastVerified: V,
  },
  {
    id: "redzikowo",
    name: "Aegis Ashore Poland, Redzikowo",
    short: "Redzikowo",
    lat: 54.479,
    lon: 17.108,
    operator: "USA",
    hostCountry: "POL",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "The second European Aegis Ashore site, declared operational in November 2024 — 230 km from Kaliningrad, completing the missile-defence architecture.",
    source: "US Missile Defense Agency",
    sourceUrl: "https://www.mda.mil/",
    lastVerified: V,
  },
  {
    id: "poznan",
    name: "Camp Kościuszko, Poznań",
    short: "Poznań",
    lat: 52.427,
    lon: 16.879,
    operator: "USA",
    hostCountry: "POL",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "Forward HQ of US V Corps and the first permanent US garrison on Polish soil, established 2023 — a deliberate step past the rotational model.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "mk-airbase",
    name: "Mihail Kogălniceanu Air Base",
    short: "MK Air Base",
    lat: 44.3622,
    lon: 28.4883,
    operator: "USA",
    hostCountry: "ROU",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The largest US presence on the Black Sea, 25 km from Constanța, being expanded by Romania into the biggest NATO base in Europe.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "incirlik",
    name: "Incirlik Air Base",
    short: "Incirlik",
    lat: 37.0017,
    lon: 35.4259,
    operator: "USA",
    hostCountry: "TUR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Long reported as the largest US B61 storage site in Europe. Turkish permission has been withheld for specific operations more than once, which makes this the clearest case of a base whose value depends on the host's politics.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "kurecik",
    name: "Kürecik Radar Station",
    short: "Kürecik",
    lat: 38.2833,
    lon: 37.7833,
    operator: "USA",
    hostCountry: "TUR",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "AN/TPY-2 X-band radar, the forward sensor of NATO missile defence. Iran has publicly threatened it; Türkiye restricts what data may be shared with Israel.",
    source: "NATO ballistic missile defence fact sheet",
    sourceUrl: "https://www.nato.int/cps/en/natohq/topics_49635.htm",
    lastVerified: V,
  },
  {
    id: "souda-bay",
    name: "Naval Support Activity Souda Bay",
    short: "Souda Bay",
    lat: 35.5322,
    lon: 24.1497,
    operator: "USA",
    hostCountry: "GRC",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "The deep-water anchorage and runway that give the US eastern Mediterranean access independent of Turkish permission — which is why its use has grown since 2019.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
  },
  {
    id: "keflavik",
    name: "Keflavík Air Base",
    short: "Keflavík",
    lat: 63.985,
    lon: -22.6056,
    operator: "USA",
    hostCountry: "ISL",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Closed as a permanent base in 2006, reopened for rotational P-8 anti-submarine patrols from 2016 as Russian submarine activity in the GIUK gap recovered.",
    source: EUCOM,
    sourceUrl: EUCOM_URL,
    lastVerified: V,
  },
  {
    id: "bondsteel",
    name: "Camp Bondsteel",
    short: "Bondsteel",
    lat: 42.3667,
    lon: 21.25,
    operator: "USA",
    hostCountry: "XKX",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "The US contribution to NATO's KFOR mission and the largest US base in the Balkans since 1999.",
    source: "NATO KFOR",
    sourceUrl: "https://jfcnaples.nato.int/kfor",
    lastVerified: V,
    hostNote: "In Kosovo, whose independence is recognised by most NATO members and rejected by Serbia, Russia and China.",
  },
  {
    id: "akrotiri",
    name: "RAF Akrotiri",
    short: "Akrotiri",
    lat: 34.59,
    lon: 32.988,
    operator: "GBR",
    hostCountry: "CYP",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "A British sovereign base, not a base in Cyprus: the launch point for UK strikes on Yemen and Syria and the main Levant ISR platform.",
    source: "UK Ministry of Defence",
    sourceUrl: "https://www.gov.uk/government/organisations/ministry-of-defence",
    lastVerified: V,
    hostNote: "Sovereign Base Area — UK territory under the 1960 Treaty of Establishment, geographically inside Cyprus but outside Cypriot sovereignty.",
  },
  {
    id: "ayios-nikolaos",
    name: "Ayios Nikolaos Station, Dhekelia",
    short: "Ayios Nikolaos",
    lat: 34.98,
    lon: 33.95,
    operator: "GBR",
    hostCountry: "CYP",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "UK signals-intelligence station covering the eastern Mediterranean, Levant and Iran, and a Five Eyes collection node.",
    source: "UK Ministry of Defence",
    sourceUrl: "https://www.gov.uk/government/organisations/ministry-of-defence",
    lastVerified: V,
    hostNote: "Inside the Dhekelia Sovereign Base Area, UK territory under the 1960 Treaty of Establishment.",
  },

  // ---- Middle East
  {
    id: "al-udeid",
    name: "Al Udeid Air Base",
    short: "Al Udeid",
    lat: 25.1173,
    lon: 51.315,
    operator: "USA",
    hostCountry: "QAT",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Forward HQ of US Central Command and the Combined Air Operations Center that runs every US air sortie from Egypt to Kazakhstan. The single most important US air base outside the United States.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "nsa-bahrain",
    name: "Naval Support Activity Bahrain",
    short: "NSA Bahrain",
    lat: 26.21,
    lon: 50.61,
    operator: "USA",
    hostCountry: "BHR",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "HQ US Fifth Fleet and Combined Maritime Forces — the command responsible for the Strait of Hormuz and Bab al-Mandab, 200 km from the Iranian coast.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "al-dhafra",
    name: "Al Dhafra Air Base",
    short: "Al Dhafra",
    lat: 24.2482,
    lon: 54.5477,
    operator: "USA",
    hostCountry: "ARE",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "US tanker, ISR and fifth-generation fighter base; F-22s and F-35s have deployed here repeatedly during Gulf escalations.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "ali-al-salem",
    name: "Ali Al Salem Air Base",
    short: "Ali Al Salem",
    lat: 29.3467,
    lon: 47.5206,
    operator: "USA",
    hostCountry: "KWT",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The closest US combat air base to Iraq and Iran, 40 km from the Iraqi border; Patriot and counter-rocket defences have engaged repeatedly since 2020.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "camp-arifjan",
    name: "Camp Arifjan",
    short: "Arifjan",
    lat: 28.8667,
    lon: 48.1583,
    operator: "USA",
    hostCountry: "KWT",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "The US Army's logistics hub for the whole Central Command area and the pre-positioned equipment set that makes rapid reinforcement of the Gulf possible.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "muwaffaq-salti",
    name: "Muwaffaq Salti Air Base, Azraq",
    short: "Azraq",
    lat: 31.8256,
    lon: 36.7817,
    operator: "USA",
    hostCountry: "JOR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The US air base closest to Syria and the western approach to Iraq; expanded substantially from 2016 and used for counter-ISIS and air-defence missions.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "al-asad",
    name: "Ain al-Asad Air Base",
    short: "Al Asad",
    lat: 33.7856,
    lon: 42.4412,
    operator: "USA",
    hostCountry: "IRQ",
    branch: "air",
    status: "reported",
    confidence: "reported",
    role: "Struck by Iranian ballistic missiles in January 2020 and by militia rockets many times since. Under the 2024 US-Iraq agreement the coalition mission here was to wind down through 2025-26; the current residual presence is not publicly fixed.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "erbil",
    name: "Erbil Air Base",
    short: "Erbil",
    lat: 36.2376,
    lon: 43.9631,
    operator: "USA",
    hostCountry: "IRQ",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The coalition base in Iraqi Kurdistan, hit by Iranian ballistic missiles in March 2022 and by drones repeatedly; expected to outlast the presence in federal Iraq.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },
  {
    id: "al-tanf",
    name: "Al Tanf Garrison",
    short: "Al Tanf",
    lat: 33.5,
    lon: 38.6,
    operator: "USA",
    hostCountry: "SYR",
    branch: "land",
    status: "reported",
    confidence: "reported",
    role: "A small garrison astride the Baghdad-Damascus highway, positioned to sit on the Iranian land corridor to the Levant. Its status after the December 2024 collapse of the Assad government has not been publicly settled.",
    source: CENTCOM,
    sourceUrl: CENTCOM_URL,
    lastVerified: V,
  },

  // ---- Africa
  {
    id: "camp-lemonnier",
    name: "Camp Lemonnier",
    short: "Lemonnier",
    lat: 11.5472,
    lon: 43.1595,
    operator: "USA",
    hostCountry: "DJI",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "The only enduring US base in Africa: the Horn of Africa task force, ISR over Yemen and Somalia, and a berth at the Bab al-Mandab approach — four kilometres from China's only overseas base.",
    source: "US Africa Command",
    sourceUrl: "https://www.africom.mil/",
    lastVerified: V,
  },
  {
    id: "airbase-201",
    name: "Air Base 201, Agadez",
    short: "Agadez",
    lat: 16.96,
    lon: 8.0,
    operator: "USA",
    hostCountry: "NER",
    branch: "air",
    status: "closed",
    confidence: "documented",
    role: "A purpose-built US drone base for the Sahel, roughly $110m of construction. Niger's junta revoked the status-of-forces agreement in March 2024 and the US completed withdrawal on 5 September 2024, leaving no comparable ISR coverage of the central Sahel.",
    source: "US Africa Command",
    sourceUrl: "https://www.africom.mil/",
    lastVerified: V,
  },

  // ---- Indo-Pacific
  {
    id: "kadena",
    name: "Kadena Air Base",
    short: "Kadena",
    lat: 26.3516,
    lon: 127.7692,
    operator: "USA",
    hostCountry: "JPN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The largest US combat air base in the Pacific and the closest to Taiwan at 640 km. Its permanent F-15C wing retired in 2022 and has been replaced by rotational fighters, which is itself a contested policy question.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "yokosuka",
    name: "Fleet Activities Yokosuka",
    short: "Yokosuka",
    lat: 35.2931,
    lon: 139.6717,
    operator: "USA",
    hostCountry: "JPN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "HQ US Seventh Fleet and the only forward-deployed US carrier strike group anywhere — the single installation that most shortens American response time in the Western Pacific.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "sasebo",
    name: "Fleet Activities Sasebo",
    short: "Sasebo",
    lat: 33.16,
    lon: 129.71,
    operator: "USA",
    hostCountry: "JPN",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Home of the forward-deployed US amphibious ready group and mine countermeasures force, at the mouth of the East China Sea.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "iwakuni",
    name: "Marine Corps Air Station Iwakuni",
    short: "Iwakuni",
    lat: 34.1436,
    lon: 132.2356,
    operator: "USA",
    hostCountry: "JPN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The US Marine Corps' F-35B base and the carrier air wing's shore establishment — the fixed-wing complement to the Yokosuka carrier.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "misawa",
    name: "Misawa Air Base",
    short: "Misawa",
    lat: 40.7032,
    lon: 141.3683,
    operator: "USA",
    hostCountry: "JPN",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Northern Japan's joint US-Japanese air base, with a major signals-intelligence site covering the Sea of Okhotsk and Russian Pacific Fleet movements.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "camp-humphreys",
    name: "Camp Humphreys",
    short: "Humphreys",
    lat: 36.964,
    lon: 127.03,
    operator: "USA",
    hostCountry: "KOR",
    branch: "land",
    status: "active",
    confidence: "documented",
    role: "The largest US overseas base by area anywhere. Headquarters moved here from Seoul in 2018 specifically to get out of DPRK artillery range.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "osan",
    name: "Osan Air Base",
    short: "Osan",
    lat: 37.0906,
    lon: 127.0297,
    operator: "USA",
    hostCountry: "KOR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "HQ Seventh Air Force and the northernmost US air base on the peninsula — within range of DPRK long-range artillery and rocket systems.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "kunsan",
    name: "Kunsan Air Base",
    short: "Kunsan",
    lat: 35.9038,
    lon: 126.6159,
    operator: "USA",
    hostCountry: "KOR",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The 8th Fighter Wing on the Yellow Sea coast, sited to keep a fighter base usable if the northern airfields are suppressed.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "andersen",
    name: "Andersen Air Force Base",
    short: "Andersen",
    lat: 13.584,
    lon: 144.924,
    operator: "USA",
    hostCountry: "GUM",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "The US bomber base inside the second island chain and the reason Guam is the declared target set for Chinese intermediate-range missiles.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
    hostNote: "Guam is an unincorporated US territory, so this is sovereign US soil rather than an overseas basing agreement.",
  },
  {
    id: "naval-base-guam",
    name: "Naval Base Guam, Apra Harbor",
    short: "Apra Harbor",
    lat: 13.4433,
    lon: 144.6558,
    operator: "USA",
    hostCountry: "GUM",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Forward submarine base and the deep-water logistics anchor for any Western Pacific campaign; the Marine Corps' Camp Blaz is on the same island.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
    hostNote: "Unincorporated US territory.",
  },
  {
    id: "diego-garcia",
    name: "Diego Garcia",
    short: "Diego Garcia",
    lat: -7.3133,
    lon: 72.4111,
    operator: "USA",
    hostCountry: "IOT",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "A joint UK-US atoll base in the middle of the Indian Ocean: bomber dispersal, submarine tender, pre-positioning ships. No neighbour can deny access to it because it has no neighbours.",
    source: "UK Ministry of Defence / US Navy",
    sourceUrl: "https://www.gov.uk/government/organisations/ministry-of-defence",
    lastVerified: V,
    hostNote: "British Indian Ocean Territory, leased to the US. Under the 2024-25 UK-Mauritius agreement sovereignty transfers to Mauritius with the base retained on a 99-year lease.",
  },
  {
    id: "darwin",
    name: "Darwin (Marine Rotational Force)",
    short: "Darwin",
    lat: -12.4147,
    lon: 130.877,
    operator: "USA",
    hostCountry: "AUS",
    branch: "joint",
    status: "active",
    confidence: "documented",
    role: "A rotational Marine task force each dry season since 2012, hosted on Australian bases rather than a US installation — the model the US is trying to extend across the region.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "tindal",
    name: "RAAF Base Tindal",
    short: "Tindal",
    lat: -14.5211,
    lon: 132.3783,
    operator: "AUS",
    hostCountry: "AUS",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "Being rebuilt with US funding to take six B-52s and their fuel — a bomber base south of the range of most Chinese strike systems.",
    source: "Australian Department of Defence",
    sourceUrl: "https://www.defence.gov.au/",
    lastVerified: V,
  },
  {
    id: "hmas-stirling",
    name: "HMAS Stirling",
    short: "Stirling",
    lat: -32.2333,
    lon: 115.6833,
    operator: "AUS",
    hostCountry: "AUS",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Submarine Rotational Force-West under AUKUS Pillar 1: US and UK nuclear attack submarines forward-based in Western Australia from 2027, ahead of Australia's own boats.",
    source: "Australian Department of Defence",
    sourceUrl: "https://www.defence.gov.au/",
    lastVerified: V,
  },
  {
    id: "pine-gap",
    name: "Joint Defence Facility Pine Gap",
    short: "Pine Gap",
    lat: -23.799,
    lon: 133.737,
    operator: "USA",
    hostCountry: "AUS",
    branch: "space-radar",
    status: "active",
    confidence: "documented",
    role: "Joint US-Australian satellite ground station: signals intelligence, missile-launch detection and targeting support. The most consequential intelligence facility in the southern hemisphere.",
    source: "Australian Department of Defence",
    sourceUrl: "https://www.defence.gov.au/",
    lastVerified: V,
  },
  {
    id: "basa",
    name: "Basa Air Base",
    short: "Basa",
    lat: 14.986,
    lon: 120.492,
    operator: "USA",
    hostCountry: "PHL",
    branch: "air",
    status: "active",
    confidence: "documented",
    role: "An Enhanced Defense Cooperation Agreement site, upgraded for rotational US aircraft — access rather than a base, which is the post-1992 Philippine model.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "santa-ana",
    name: "Naval Base Camilo Osias, Santa Ana",
    short: "Santa Ana",
    lat: 18.488,
    lon: 122.148,
    operator: "USA",
    hostCountry: "PHL",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "One of the four EDCA sites added in 2023, at the northern tip of Luzon facing the Bashi Channel — the PLA Navy's route into the Philippine Sea and the closest Philippine access point to Taiwan.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },
  {
    id: "subic",
    name: "Subic Bay",
    short: "Subic",
    lat: 14.7944,
    lon: 120.27,
    operator: "USA",
    hostCountry: "PHL",
    branch: "naval",
    status: "reported",
    confidence: "reported",
    role: "The US Navy's main Asian base until the Philippine Senate ended the bases agreement in 1992. Now a commercial port with recurring US ship visits and repair work, and a recurring political argument about returning.",
    source: INDOPACOM,
    sourceUrl: INDOPACOM_URL,
    lastVerified: V,
  },

  // ---- Western hemisphere
  {
    id: "guantanamo",
    name: "Naval Station Guantanamo Bay",
    short: "Guantánamo",
    lat: 19.9058,
    lon: -75.2072,
    operator: "USA",
    hostCountry: "CUB",
    branch: "naval",
    status: "active",
    confidence: "documented",
    role: "Held under a 1903 lease that Cuba has rejected as invalid since 1959 while the United States continues to occupy it — the longest-running base dispute anywhere.",
    source: BSR,
    sourceUrl: BSR_URL,
    lastVerified: V,
    hostNote: "Cuba disputes the validity of the lease and refuses the annual payment. The United States treats the arrangement as in force indefinitely.",
  },
];
