/** Generated by scripts/build-mexico-homicide.mjs — do not edit by hand. */
export type MexicoStateHomicide = {
  clave: number;
  name: string;
  homicides: number;
  ratePer100k: number;
};

export const MEXICO_HOMICIDE_YEAR = 2024;
export const MEXICO_HOMICIDE_SOURCE =
  "datos.gob.mx incidencia_delictiva (tipo_delito=Homicidio); rate uses INEGI 2020 population";

export const MEXICO_HOMICIDE_STATES: MexicoStateHomicide[] = [
  {
    "clave": 2,
    "name": "Baja California",
    "homicides": 2542,
    "ratePer100k": 313.4
  },
  {
    "clave": 15,
    "name": "México",
    "homicides": 3562,
    "ratePer100k": 209.7
  },
  {
    "clave": 6,
    "name": "Colima",
    "homicides": 877,
    "ratePer100k": 119.8
  },
  {
    "clave": 23,
    "name": "Quintana Roo",
    "homicides": 1487,
    "ratePer100k": 80
  },
  {
    "clave": 17,
    "name": "Morelos",
    "homicides": 1627,
    "ratePer100k": 67.8
  },
  {
    "clave": 12,
    "name": "Guerrero",
    "homicides": 1800,
    "ratePer100k": 63.8
  },
  {
    "clave": 11,
    "name": "Guanajuato",
    "homicides": 3772,
    "ratePer100k": 61.1
  },
  {
    "clave": 8,
    "name": "Chihuahua",
    "homicides": 2016,
    "ratePer100k": 53.8
  },
  {
    "clave": 16,
    "name": "Michoacán",
    "homicides": 2519,
    "ratePer100k": 53.1
  },
  {
    "clave": 20,
    "name": "Oaxaca",
    "homicides": 2203,
    "ratePer100k": 50.8
  },
  {
    "clave": 27,
    "name": "Tabasco",
    "homicides": 1180,
    "ratePer100k": 49.1
  },
  {
    "clave": 32,
    "name": "Zacatecas",
    "homicides": 792,
    "ratePer100k": 48.9
  },
  {
    "clave": 26,
    "name": "Sonora",
    "homicides": 1423,
    "ratePer100k": 48.3
  },
  {
    "clave": 25,
    "name": "Sinaloa",
    "homicides": 1419,
    "ratePer100k": 46.9
  },
  {
    "clave": 19,
    "name": "Nuevo León",
    "homicides": 2111,
    "ratePer100k": 36.5
  },
  {
    "clave": 18,
    "name": "Nayarit",
    "homicides": 386,
    "ratePer100k": 31.3
  },
  {
    "clave": 14,
    "name": "Jalisco",
    "homicides": 2411,
    "ratePer100k": 28.9
  },
  {
    "clave": 28,
    "name": "Tamaulipas",
    "homicides": 1018,
    "ratePer100k": 28.9
  },
  {
    "clave": 21,
    "name": "Puebla",
    "homicides": 1847,
    "ratePer100k": 28.1
  },
  {
    "clave": 7,
    "name": "Chiapas",
    "homicides": 1426,
    "ratePer100k": 25.7
  },
  {
    "clave": 24,
    "name": "San Luis Potosí",
    "homicides": 696,
    "ratePer100k": 24.7
  },
  {
    "clave": 4,
    "name": "Campeche",
    "homicides": 197,
    "ratePer100k": 22
  },
  {
    "clave": 13,
    "name": "Hidalgo",
    "homicides": 428,
    "ratePer100k": 21
  },
  {
    "clave": 30,
    "name": "Veracruz",
    "homicides": 1767,
    "ratePer100k": 20.9
  },
  {
    "clave": 9,
    "name": "Ciudad de México",
    "homicides": 1663,
    "ratePer100k": 18.1
  },
  {
    "clave": 22,
    "name": "Querétaro",
    "homicides": 548,
    "ratePer100k": 18.1
  },
  {
    "clave": 3,
    "name": "Baja California Sur",
    "homicides": 142,
    "ratePer100k": 17.8
  },
  {
    "clave": 1,
    "name": "Aguascalientes",
    "homicides": 246,
    "ratePer100k": 16.6
  },
  {
    "clave": 10,
    "name": "Durango",
    "homicides": 284,
    "ratePer100k": 15.2
  },
  {
    "clave": 5,
    "name": "Coahuila",
    "homicides": 399,
    "ratePer100k": 12.6
  },
  {
    "clave": 29,
    "name": "Tlaxcala",
    "homicides": 158,
    "ratePer100k": 11.2
  },
  {
    "clave": 31,
    "name": "Yucatán",
    "homicides": 201,
    "ratePer100k": 8.7
  }
];

