/**
 * Russian export trunk lines.
 *
 * These are the entries the status field exists for. One line has been blown up,
 * one was stopped by Russia's own counter-sanction, one has a live leg and a
 * stopped leg under the same name, and two carry more than they did in 2021
 * because the westbound routes closed. A layer that drew all seven the same way
 * would be worse than no layer.
 */
import type { Pipeline } from "./pipelines.ts";

const GAZPROM = "Gazprom";
const TRANSNEFT = "Transneft";

export const RUS_PIPELINES: Pipeline[] = [
  {
    id: "nord-stream-1",
    name: "Nord Stream 1",
    short: "Nord Stream 1",
    product: "gas",
    status: "damaged",
    operator: "Nord Stream AG (Gazprom-controlled)",
    operatorState: "RUS",
    transit: ["RUS", "DEU"],
    capacity: { value: 55, unit: "bcm/yr" },
    path: [
      [60.72, 28.73],
      [59.9, 28.3],
      [59.4, 27.0],
      [59.0, 24.0],
      [58.6, 21.5],
      [57.6, 20.0],
      [56.3, 18.8],
      [55.53, 15.7],
      [55.2, 16.5],
      [54.8, 15.0],
      [54.5, 14.0],
      [54.14, 13.66],
    ],
    statusNote:
      "Both strings ruptured by underwater explosions north-east of Bornholm on 26 September 2022. One of the two Nord Stream 2 strings survived; neither Nord Stream 1 string did. Flows had already been cut to zero that August on a maintenance pretext, so the sabotage ended a line that was not running.",
    since: "2022-09-26",
    kind: "de-facto",
    confidence: "documented",
    source: "Swedish/Danish/German investigations; Gazprom flow notices",
    sourceUrl: "https://www.nord-stream.com/",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "nord-stream-2",
    name: "Nord Stream 2",
    short: "Nord Stream 2",
    product: "gas",
    status: "idle",
    operator: "Nord Stream 2 AG (Gazprom)",
    operatorState: "RUS",
    transit: ["RUS", "DEU"],
    capacity: { value: 55, unit: "bcm/yr" },
    path: [
      [59.66, 28.35],
      [59.5, 27.5],
      [59.3, 25.5],
      [58.8, 22.5],
      [57.9, 20.6],
      [56.6, 19.2],
      [55.5, 17.0],
      [54.9, 15.3],
      [54.6, 14.2],
      [54.14, 13.66],
    ],
    statusNote:
      "Never commissioned. German certification was halted on 22 February 2022, two days before the invasion, and the operating company entered Swiss insolvency proceedings. One of its two strings survived the September 2022 sabotage and is technically intact and pressurised, which is why this is idle rather than damaged.",
    since: "2022-02-22",
    kind: "state-action",
    confidence: "documented",
    source: "German Federal Ministry for Economic Affairs certification suspension",
    sourceUrl: "https://www.nord-stream2.com/",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "druzhba-north",
    name: "Druzhba — northern leg (Belarus–Poland–Germany)",
    short: "Druzhba N",
    product: "crude",
    status: "reduced",
    operator: TRANSNEFT,
    operatorState: "RUS",
    transit: ["RUS", "BLR", "POL", "DEU"],
    capacity: { value: 1.0, unit: "mmbd" },
    path: [
      [53.2, 50.15],
      [53.4, 48.5],
      [53.2, 45.0],
      [52.6, 41.0],
      [52.5, 36.5],
      [52.7, 33.0],
      [52.4, 31.0],
      [52.05, 29.27],
      [52.2, 26.5],
      [52.3, 23.6],
      [52.2, 22.0],
      [52.4, 20.0],
      [52.6, 17.0],
      [52.9, 15.2],
      [53.06, 14.28],
    ],
    statusNote:
      "Germany stopped taking Russian crude at Schwedt from January 2023 under its own commitment rather than an EU import ban, and Poland's contract lapsed the following month. The line still moves oil inside Russia and Belarus and has been struck repeatedly by Ukrainian drones at pumping stations; the westbound leg past Belarus carries little to nothing.",
    since: "2023-01-01",
    kind: "state-action",
    confidence: "documented",
    source: "EU Regulation 833/2014 Art. 3m and German/Polish national commitments",
    sourceUrl: "https://eur-lex.europa.eu/eli/reg/2014/833/oj",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "druzhba-south",
    name: "Druzhba — southern leg (Ukraine–Hungary–Slovakia)",
    short: "Druzhba S",
    product: "crude",
    status: "operating",
    operator: TRANSNEFT,
    operatorState: "RUS",
    transit: ["RUS", "BLR", "UKR", "HUN", "SVK"],
    capacity: { value: 0.3, unit: "mmbd" },
    path: [
      [52.05, 29.27],
      [51.6, 28.0],
      [50.9, 26.0],
      [50.3, 24.5],
      [49.7, 23.0],
      [48.9, 22.2],
      [48.7, 21.6],
      [48.4, 20.5],
      [47.9, 19.5],
      [47.3, 18.6],
    ],
    statusNote:
      "The one leg still delivering Russian crude into the EU. Hungary and Slovakia hold a landlocked exemption from the EU crude import ban under Art. 3m(3) of Regulation 833/2014, so this runs while the northern leg does not. It has been interrupted several times by strikes on Russian pumping stations and by transit-fee disputes, each lasting days rather than weeks.",
    since: "2022-06-03",
    kind: "treaty",
    confidence: "documented",
    source: "EU Regulation 833/2014 Art. 3m(3) landlocked derogation",
    sourceUrl: "https://eur-lex.europa.eu/eli/reg/2014/833/oj",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "yamal-europe",
    name: "Yamal–Europe",
    short: "Yamal",
    product: "gas",
    status: "suspended",
    operator: `${GAZPROM} / EuRoPol GAZ`,
    operatorState: "RUS",
    transit: ["RUS", "BLR", "POL", "DEU"],
    capacity: { value: 33, unit: "bcm/yr" },
    path: [
      [57.05, 34.96],
      [56.0, 33.0],
      [55.0, 31.0],
      [54.2, 29.5],
      [53.4, 28.0],
      [53.0, 26.7],
      [52.6, 25.0],
      [52.3, 23.6],
      [52.5, 22.0],
      [53.0, 21.5],
      [52.9, 20.6],
      [52.65, 19.07],
      [52.5, 16.2],
      [52.35, 14.55],
    ],
    statusNote:
      "Stopped by Russia, not by Europe. Poland nationalised Gazprom's stake in the Polish operator EuRoPol GAZ in April 2022 and Russia placed that company under counter-sanctions on 11 May 2022, ending westward flow. The line spent much of 2022 running in reverse, Germany to Poland, before going quiet.",
    since: "2022-05-11",
    kind: "state-action",
    confidence: "documented",
    source: "Russian Government Decree 851 counter-sanctions list",
    sourceUrl: "https://www.gazprom.com/projects/yamal-europe/",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "turkstream",
    name: "TurkStream / Balkan Stream",
    short: "TurkStream",
    product: "gas",
    status: "operating",
    operator: `${GAZPROM} / BOTAŞ`,
    operatorState: "RUS",
    transit: ["RUS", "TUR", "BGR", "SRB", "HUN"],
    capacity: { value: 31.5, unit: "bcm/yr" },
    path: [
      [44.87, 37.34],
      [44.3, 36.5],
      [43.5, 35.0],
      [42.8, 33.0],
      [42.2, 31.0],
      [41.7, 29.3],
      [41.39, 28.13],
      [41.4, 27.4],
      [41.8, 26.8],
      [42.2, 26.3],
      [42.6, 25.5],
      [43.4, 25.9],
      [44.0, 22.6],
      [44.8, 20.5],
      [45.8, 18.9],
    ],
    statusNote:
      "The last pipeline route for Russian gas into the EU after the Ukrainian transit contract expired on 1 January 2025. Its second string, marketed onward as Balkan Stream, is now the sole supply line for Hungary and Serbia, which is why both states are the loudest opponents of extending sanctions to it. Not itself sanctioned.",
    since: "2025-01-01",
    kind: "de-facto",
    confidence: "documented",
    source: "ENTSOG transparency platform; Gazprom Export",
    sourceUrl: "https://transparency.entsog.eu/",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "blue-stream",
    name: "Blue Stream",
    short: "Blue Stream",
    product: "gas",
    status: "operating",
    operator: `${GAZPROM} / Eni`,
    operatorState: "RUS",
    transit: ["RUS", "TUR"],
    capacity: { value: 16, unit: "bcm/yr" },
    path: [
      [44.6, 38.1],
      [44.0, 37.5],
      [43.2, 37.0],
      [42.4, 36.7],
      [41.4, 36.2],
      [40.8, 36.0],
      [40.2, 35.5],
      [39.93, 32.86],
    ],
    statusNote:
      "Türkiye's older Black Sea route, running to Samsun and inland to Ankara. Not sanctioned — Türkiye is not applying EU or US energy measures and has become the principal buyer at the margin, which is what makes this and TurkStream together the pressure valve on Russian gas.",
    since: "2003-02-20",
    kind: "treaty",
    confidence: "documented",
    source: "Gazprom project record; BOTAŞ import statistics",
    sourceUrl: "https://www.gazprom.com/projects/blue-stream/",
    lastVerified: "2026-09-20",
  },
  {
    id: "power-of-siberia",
    name: "Power of Siberia",
    short: "Power of Siberia",
    product: "gas",
    status: "operating",
    operator: `${GAZPROM} / CNPC`,
    operatorState: "RUS",
    transit: ["RUS", "CHN"],
    capacity: { value: 38, unit: "bcm/yr" },
    path: [
      [60.5, 121.0],
      [59.0, 122.5],
      [57.0, 124.0],
      [55.0, 125.5],
      [53.0, 126.5],
      [51.5, 127.2],
      [50.27, 127.53],
      [47.0, 129.5],
      [45.7, 126.6],
      [43.9, 125.3],
      [41.8, 123.4],
      [38.9, 117.2],
      [36.7, 117.0],
      [34.3, 117.2],
      [32.1, 118.8],
      [31.2, 121.5],
    ],
    statusNote:
      "Reached its 38 bcm design capacity at the end of 2024 and is the only pipeline replacing any meaningful share of the lost European gas market — against roughly 150 bcm that once went west, which is the number to hold in mind. Power of Siberia 2 across Mongolia remains an intergovernmental memorandum rather than a construction project.",
    since: "2019-12-02",
    kind: "treaty",
    confidence: "documented",
    source: "Gazprom/CNPC 30-year supply contract",
    sourceUrl: "https://www.gazprom.com/projects/power-of-siberia/",
    lastVerified: "2026-09-20",
    zone: "indopacific",
  },
  {
    id: "espo",
    name: "Eastern Siberia–Pacific Ocean (ESPO)",
    short: "ESPO",
    product: "crude",
    status: "operating",
    operator: TRANSNEFT,
    operatorState: "RUS",
    transit: ["RUS", "CHN"],
    capacity: { value: 1.6, unit: "mmbd" },
    path: [
      [56.1, 98.0],
      [55.4, 104.0],
      [55.0, 110.0],
      [54.6, 116.0],
      [54.0, 124.0],
      [51.5, 128.5],
      [49.0, 130.5],
      [47.0, 133.0],
      [45.0, 133.5],
      [43.5, 132.0],
      [42.75, 132.9],
    ],
    statusNote:
      "The pivot east, in one line: Taishet to the Pacific at Kozmino with a branch to Daqing. Kozmino loadings are where the shadow fleet and the G7 price cap meet — most ESPO Blend now moves above the cap on tankers without Western insurance, and many of the vessels carrying it are OFAC- or EU-designated.",
    since: "2012-12-25",
    kind: "de-facto",
    confidence: "documented",
    source: "Transneft system description; Kozmino loading programmes",
    sourceUrl: "https://en.transneft.ru/",
    lastVerified: "2026-09-20",
    zone: "indopacific",
  },
  {
    id: "skhv",
    name: "Sakhalin–Khabarovsk–Vladivostok",
    short: "SKV",
    product: "gas",
    status: "operating",
    operator: GAZPROM,
    operatorState: "RUS",
    transit: ["RUS"],
    capacity: { value: 6, unit: "bcm/yr" },
    path: [
      [53.2, 142.9],
      [52.2, 142.0],
      [51.3, 141.2],
      [51.5, 140.3],
      [50.9, 139.0],
      [50.0, 137.0],
      [48.5, 135.1],
      [46.5, 133.5],
      [44.5, 132.5],
      [43.12, 131.89],
    ],
    statusNote:
      "Domestic, and listed because it is the landward half of the Sakhalin export complex that Japan still buys LNG from under a carve-out from its own Russian energy restrictions. Sakhalin-2's operating company was re-domiciled by Russian decree in 2022 and Shell wrote off its stake.",
    since: "2011-09-08",
    kind: "treaty",
    confidence: "documented",
    source: "Gazprom project record",
    sourceUrl: "https://www.gazprom.com/projects/skv/",
    lastVerified: "2026-09-20",
    zone: "korea",
  },
  {
    id: "cpc",
    name: "Caspian Pipeline Consortium (Tengiz–Novorossiysk)",
    short: "CPC",
    product: "crude",
    status: "operating",
    operator: "Caspian Pipeline Consortium",
    operatorState: "KAZ",
    transit: ["KAZ", "RUS"],
    capacity: { value: 1.6, unit: "mmbd" },
    path: [
      [46.13, 53.47],
      [46.6, 51.5],
      [46.9, 49.0],
      [46.6, 47.0],
      [46.3, 45.0],
      [45.9, 43.0],
      [45.4, 41.5],
      [45.0, 39.5],
      [44.7, 38.3],
      [44.62, 37.79],
    ],
    statusNote:
      "Kazakh crude, not Russian, but it leaves through a Russian port and its loading buoys at Novorossiysk have been repeatedly shut by Russian court orders, storm damage and Ukrainian drone strikes. CPC Blend is not under the price cap; the vulnerability is physical and jurisdictional rather than legal, which is exactly why Kazakhstan keeps trying to route barrels via BTC.",
    since: "2001-10-01",
    kind: "treaty",
    confidence: "documented",
    source: "CPC shareholder disclosures; Kazakh energy ministry statements",
    sourceUrl: "https://www.cpc.ru/en",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
];
