/**
 * Gulf and Levant lines.
 *
 * Every entry here exists because of a chokepoint. Petroline and ADCOP are the
 * two routes that can put Gulf crude on a ship outside Hormuz; the Iraqi and Arab
 * Gas lines are the ones a conflict has already stopped. Read them against the
 * Hormuz and Bab al-Mandab entries in the chokepoint registry — the transit lists
 * are the join.
 */
import type { Pipeline } from "./pipelines.ts";

export const GULF_PIPELINES: Pipeline[] = [
  {
    id: "petroline",
    name: "East–West Crude Oil Pipeline (Petroline)",
    short: "Petroline",
    product: "crude",
    status: "operating",
    operator: "Saudi Aramco",
    operatorState: "SAU",
    transit: ["SAU"],
    capacity: { value: 5.0, unit: "mmbd" },
    path: [
      [25.93, 49.67],
      [25.6, 48.0],
      [25.4, 46.5],
      [25.2, 44.5],
      [25.0, 42.5],
      [24.7, 40.5],
      [24.4, 39.2],
      [24.09, 38.06],
    ],
    statusNote:
      "The largest single Hormuz bypass in existence: Abqaiq to Yanbu on the Red Sea, around 5 million b/d of capacity against roughly 20 million b/d moving through the strait. It swaps one chokepoint for another — Yanbu barrels still have to pass Bab al-Mandab or go north through Suez — and its pumping stations were hit by drones in 2019 and again by Houthi claims since. Operational status moves on attack and repair cycles: read pipeline headlines in the energy panel and any row in data/infrastructure-overlays.json before treating 'operating' as today's fact.",
    since: "1981-06-01",
    kind: "treaty",
    confidence: "documented",
    source: "Saudi Aramco disclosures; EIA World Oil Transit Chokepoints",
    sourceUrl: "https://www.aramco.com/",
    lastVerified: "2026-09-20",
    zone: "hormuz",
  },
  {
    id: "adcop",
    name: "Abu Dhabi Crude Oil Pipeline (Habshan–Fujairah)",
    short: "ADCOP",
    product: "crude",
    status: "operating",
    operator: "ADNOC",
    operatorState: "ARE",
    transit: ["ARE"],
    capacity: { value: 1.8, unit: "mmbd" },
    path: [
      [23.75, 53.6],
      [24.1, 54.3],
      [24.4, 55.0],
      [24.7, 55.7],
      [25.0, 56.1],
      [25.15, 56.35],
    ],
    statusNote:
      "The UAE's own Hormuz bypass, landing at Fujairah on the Gulf of Oman. Fujairah itself sits just outside the strait, which is why tanker attacks and limpet-mine incidents there in 2019 mattered out of proportion to their scale: they demonstrated that the bypass terminus is reachable too.",
    since: "2012-07-15",
    kind: "treaty",
    confidence: "documented",
    source: "ADNOC operations reporting",
    sourceUrl: "https://www.adnoc.ae/",
    lastVerified: "2026-09-20",
    zone: "hormuz",
  },
  {
    id: "dolphin",
    name: "Dolphin Gas (Ras Laffan–Taweelah)",
    short: "Dolphin",
    product: "gas",
    status: "operating",
    operator: "Dolphin Energy",
    operatorState: "QAT",
    transit: ["QAT", "ARE", "OMN"],
    capacity: { value: 20.5, unit: "bcm/yr" },
    path: [
      [25.9, 51.55],
      [25.6, 52.3],
      [25.2, 53.2],
      [24.8, 54.0],
      [24.55, 54.7],
      [24.4, 55.4],
      [24.2, 56.1],
    ],
    statusNote:
      "The only cross-border gas pipeline in the Gulf, and it ran without interruption straight through the 2017–2021 blockade of Qatar by the states it supplies. That is the entry's real content: physical interdependence outlasting a diplomatic rupture.",
    since: "2007-07-01",
    kind: "treaty",
    confidence: "documented",
    source: "Dolphin Energy shareholder disclosures",
    sourceUrl: "https://www.dolphinenergy.com/",
    lastVerified: "2026-09-20",
    zone: "hormuz",
  },
  {
    id: "kirkuk-ceyhan",
    name: "Iraq–Türkiye Pipeline (Kirkuk–Ceyhan)",
    short: "Kirkuk–Ceyhan",
    product: "crude",
    status: "suspended",
    operator: "North Oil Company / BOTAŞ",
    operatorState: "IRQ",
    transit: ["IRQ", "TUR"],
    capacity: { value: 1.5, unit: "mmbd" },
    path: [
      [35.47, 44.39],
      [35.8, 43.7],
      [36.3, 43.1],
      [36.8, 42.7],
      [37.1, 42.4],
      [37.25, 42.0],
      [37.5, 41.0],
      [37.9, 40.2],
      [37.9, 38.3],
      [37.6, 37.4],
      [37.2, 36.5],
      [36.87, 35.93],
    ],
    statusNote:
      "Halted on 25 March 2023 when an ICC tribunal found Türkiye had breached the 1973 transit agreement by allowing Kurdistan Regional Government exports without Baghdad's consent, stranding roughly 450,000 b/d. Restart has been announced and partially reversed several times since on federal–KRG revenue terms rather than on anything physical, so treat any current flow figure as reported rather than confirmed.",
    since: "2023-03-25",
    kind: "state-action",
    confidence: "reported",
    source: "ICC arbitration award; Iraqi Ministry of Oil and BOTAŞ statements",
    sourceUrl: "https://oil.gov.iq/",
    lastVerified: "2026-09-20",
    zone: "mideast",
  },
  {
    id: "arab-gas",
    name: "Arab Gas Pipeline",
    short: "Arab Gas",
    product: "gas",
    status: "idle",
    operator: "EGAS / Fajr Jordanian Gas",
    operatorState: "EGY",
    transit: ["EGY", "JOR", "SYR", "LBN"],
    capacity: { value: 10.3, unit: "bcm/yr" },
    path: [
      [31.13, 33.8],
      [30.6, 34.4],
      [29.9, 34.9],
      [29.53, 35.0],
      [30.5, 35.6],
      [31.6, 36.0],
      [32.3, 36.2],
      [33.0, 36.3],
      [33.5, 36.3],
      [34.4, 36.1],
      [34.6, 36.0],
    ],
    statusNote:
      "Repeatedly bombed in Sinai from 2011, cut by the Syrian war, and revived on paper in 2021 under a US-brokered arrangement to move Egyptian gas to Lebanon via Jordan and Syria. Egypt has since become a net gas importer, so the constraint is now supply rather than the line. Its Israeli-connected reverse leg is what actually moves.",
    since: "2011-02-05",
    kind: "de-facto",
    confidence: "reported",
    source: "Jordanian and Lebanese energy ministry statements",
    sourceUrl: "https://www.memr.gov.jo/",
    lastVerified: "2026-09-20",
    zone: "mideast",
  },
  {
    id: "iran-turkey-gas",
    name: "Tabriz–Ankara (Iran–Türkiye gas)",
    short: "Iran–TUR gas",
    product: "gas",
    status: "reduced",
    operator: "NIGC / BOTAŞ",
    operatorState: "IRN",
    transit: ["IRN", "TUR"],
    capacity: { value: 10, unit: "bcm/yr" },
    path: [
      [38.08, 46.3],
      [38.6, 45.5],
      [39.2, 44.6],
      [39.55, 44.0],
      [39.9, 43.0],
      [39.9, 41.3],
      [39.8, 39.5],
      [39.9, 37.5],
      [40.0, 35.5],
      [39.93, 32.86],
    ],
    statusNote:
      "Runs despite comprehensive US sanctions on Iranian energy, under a Turkish import contract and a series of US waivers and non-enforcement decisions; it is the clearest case on this map of a designated seller with a NATO buyer. Deliveries are interrupted most winters by Iranian domestic shortages and by bomb attacks on the Turkish section, so the status is reduced rather than operating.",
    since: "2001-12-10",
    kind: "state-action",
    confidence: "reported",
    source: "BOTAŞ import statistics; NIGC statements",
    sourceUrl: "https://www.botas.gov.tr/",
    lastVerified: "2026-09-20",
    zone: "mideast",
  },
];
