/**
 * The Southern Gas Corridor and the Caspian's eastward routes.
 *
 * The analytical point of this set is that it is the only existing corridor that
 * moves Caspian hydrocarbons to Europe without crossing Russia, and that every
 * link in it terminates in or transits Türkiye — which is also the state applying
 * neither EU nor US energy measures. The chain is deliberately entered as its
 * real separate links rather than one "Southern Gas Corridor" line, because each
 * has its own operator and could stop independently.
 */
import type { Pipeline } from "./pipelines.ts";

export const CASPIAN_PIPELINES: Pipeline[] = [
  {
    id: "btc",
    name: "Baku–Tbilisi–Ceyhan",
    short: "BTC",
    product: "crude",
    status: "operating",
    operator: "BTC Co. (BP-operated)",
    operatorState: "AZE",
    transit: ["AZE", "GEO", "TUR"],
    capacity: { value: 1.2, unit: "mmbd" },
    path: [
      [40.2, 49.47],
      [40.6, 48.3],
      [41.1, 46.6],
      [41.5, 45.2],
      [41.72, 44.78],
      [41.6, 43.5],
      [41.4, 42.9],
      [40.6, 42.0],
      [39.9, 41.3],
      [39.8, 39.5],
      [39.75, 37.9],
      [39.7, 37.0],
      [38.6, 36.5],
      [37.6, 36.2],
      [36.87, 35.93],
    ],
    statusNote:
      "Built explicitly to reach the Mediterranean without Russian or Iranian territory, and the reason Ceyhan matters. It bypasses the Turkish Straits as well, so Montreux does not apply to the barrels it carries. Kazakh crude has been added at Baku in growing volumes as an escape route from CPC.",
    since: "2006-06-04",
    kind: "treaty",
    confidence: "documented",
    source: "BTC intergovernmental agreement; BP operations reporting",
    sourceUrl: "https://www.bp.com/en_az/azerbaijan/home/who-we-are/operationsprojects/pipelines/btc.html",
    lastVerified: "2026-09-20",
  },
  {
    id: "scp",
    name: "South Caucasus Pipeline (Shah Deniz gas)",
    short: "SCP",
    product: "gas",
    status: "operating",
    operator: "SCP Co. (BP/SOCAR)",
    operatorState: "AZE",
    transit: ["AZE", "GEO", "TUR"],
    capacity: { value: 24, unit: "bcm/yr" },
    path: [
      [40.2, 49.47],
      [40.6, 48.3],
      [41.1, 46.6],
      [41.5, 45.2],
      [41.72, 44.78],
      [41.6, 43.5],
      [41.4, 42.9],
      [40.6, 42.0],
      [39.9, 41.3],
    ],
    statusNote:
      "The feed for the whole corridor: Shah Deniz gas to the Georgian–Turkish border at Türkgözü, where TANAP takes over. Expansion work to lift it past 24 bcm is the binding constraint on any promise to raise Azerbaijani deliveries to the EU.",
    since: "2006-12-01",
    kind: "treaty",
    confidence: "documented",
    source: "Southern Gas Corridor consortium disclosures",
    sourceUrl: "https://www.bp.com/en_az/azerbaijan/home/who-we-are/operationsprojects/pipelines/scp.html",
    lastVerified: "2026-09-20",
  },
  {
    id: "tanap",
    name: "Trans-Anatolian Pipeline (TANAP)",
    short: "TANAP",
    product: "gas",
    status: "operating",
    operator: "SOCAR / BOTAŞ",
    operatorState: "TUR",
    transit: ["TUR"],
    capacity: { value: 16, unit: "bcm/yr" },
    path: [
      [41.4, 42.9],
      [40.6, 42.0],
      [39.9, 41.3],
      [39.8, 39.5],
      [39.9, 37.5],
      [40.0, 35.5],
      [40.1, 33.5],
      [39.9, 31.5],
      [39.8, 30.5],
      [40.0, 29.0],
      [40.3, 27.5],
      [40.9, 26.4],
    ],
    statusNote:
      "The Anatolian middle of the corridor, from the Georgian border to the Greek border at İpsala. Most of its throughput is consumed in Türkiye; only the roughly 10 bcm handed to TAP reaches the EU, which is the ceiling on Azerbaijan as a Russian substitute.",
    since: "2018-06-12",
    kind: "treaty",
    confidence: "documented",
    source: "TANAP project company; BOTAŞ transmission data",
    sourceUrl: "https://www.tanap.com/",
    lastVerified: "2026-09-20",
  },
  {
    id: "kazakhstan-china-crude",
    name: "Kazakhstan–China crude (Atasu–Alashankou)",
    short: "KAZ–CHN crude",
    product: "crude",
    status: "operating",
    operator: "KazTransOil / CNPC",
    operatorState: "KAZ",
    transit: ["KAZ", "CHN"],
    capacity: { value: 0.4, unit: "mmbd" },
    path: [
      [48.68, 71.64],
      [48.3, 74.0],
      [47.6, 76.5],
      [46.8, 79.0],
      [45.8, 80.8],
      [45.17, 82.57],
      [44.5, 84.9],
      [44.3, 86.0],
    ],
    statusNote:
      "Kazakhstan's only significant crude route that touches neither Russia nor the Caspian tanker trade. It also runs in reverse at times to move Russian barrels into China across Kazakh territory, which is how some volumes arrive without a maritime leg and therefore without a price cap to enforce.",
    since: "2006-07-01",
    kind: "treaty",
    confidence: "documented",
    source: "KazTransOil throughput reporting",
    sourceUrl: "https://www.kaztransoil.kz/en/",
    lastVerified: "2026-09-20",
  },
  {
    id: "central-asia-china-gas",
    name: "Central Asia–China Gas Pipeline (Lines A/B/C)",
    short: "CA–CHN gas",
    product: "gas",
    status: "operating",
    operator: "CNPC with Turkmengaz/Uzbekneftegaz/KazMunayGas",
    operatorState: "CHN",
    transit: ["TKM", "UZB", "KAZ", "CHN"],
    capacity: { value: 55, unit: "bcm/yr" },
    path: [
      [38.9, 64.9],
      [39.3, 63.8],
      [39.8, 64.4],
      [40.1, 65.4],
      [41.0, 67.0],
      [41.9, 68.5],
      [42.9, 71.4],
      [43.3, 73.5],
      [43.4, 76.9],
      [44.2, 79.0],
      [44.4, 80.4],
      [44.3, 84.0],
      [43.8, 87.6],
    ],
    statusNote:
      "The larger of China's two western gas corridors and, at 55 bcm of nameplate across three lines, considerably bigger than Power of Siberia. It is the reason Turkmenistan has little commercial need of TAPI and why Chinese buyers have leverage over Gazprom's price in any Power of Siberia 2 negotiation.",
    since: "2009-12-14",
    kind: "treaty",
    confidence: "documented",
    source: "CNPC project disclosures",
    sourceUrl: "https://www.cnpc.com.cn/en/",
    lastVerified: "2026-09-20",
    zone: "indopacific",
  },
  {
    id: "tapi",
    name: "Turkmenistan–Afghanistan–Pakistan–India (TAPI)",
    short: "TAPI",
    product: "gas",
    status: "planned",
    operator: "TAPI Pipeline Company (Turkmengaz-led)",
    operatorState: "TKM",
    transit: ["TKM", "AFG", "PAK", "IND"],
    capacity: { value: 33, unit: "bcm/yr" },
    path: [
      [38.0, 62.0],
      [36.5, 62.3],
      [35.2, 62.2],
      [34.35, 62.2],
      [33.4, 63.3],
      [32.5, 64.6],
      [31.6, 65.7],
      [31.0, 66.4],
      [30.18, 67.0],
      [30.1, 68.5],
      [30.2, 70.0],
      [30.2, 71.5],
      [30.3, 73.0],
      [30.4, 74.03],
    ],
    statusNote:
      "Ground was broken on the Turkmen section in 2015 and on the Afghan section in 2024, and neither has produced a metre of commissioned line delivering gas. It is drawn here as planned because it is cited constantly in South Asian energy policy; treat the route as an intention, not infrastructure. Financing, and security across Kandahar, remain unresolved.",
    since: "2015-12-13",
    kind: "state-action",
    confidence: "reported",
    source: "Asian Development Bank project record; Turkmengaz announcements",
    sourceUrl: "https://www.adb.org/",
    lastVerified: "2026-09-20",
  },
];
