/**
 * European, North African and North American lines.
 *
 * The European set is the answer to "what replaced Russian gas": a Norwegian
 * route, an Algerian pair, and the Adriatic tail of the Southern Gas Corridor.
 * The Maghreb–Europe line is here as the control case — a pipeline stopped by a
 * quarrel between two African states with no great power involved at all.
 */
import type { Pipeline } from "./pipelines.ts";

export const ATLANTIC_PIPELINES: Pipeline[] = [
  {
    id: "tap",
    name: "Trans-Adriatic Pipeline (TAP)",
    short: "TAP",
    product: "gas",
    status: "operating",
    operator: "TAP AG",
    operatorState: "ITA",
    transit: ["GRC", "ALB", "ITA"],
    capacity: { value: 10, unit: "bcm/yr" },
    path: [
      [41.0, 26.2],
      [41.1, 25.0],
      [41.0, 23.7],
      [40.8, 22.5],
      [40.7, 21.4],
      [40.6, 20.8],
      [40.7, 20.0],
      [40.7, 19.4],
      [40.5, 19.3],
      [40.4, 18.9],
      [40.35, 18.4],
    ],
    statusNote:
      "The last leg of the Southern Gas Corridor and the only one that lands inside the EU. Its 10 bcm is the figure to weigh against the roughly 150 bcm Russia once sent west: the corridor is strategically important and quantitatively small, and doubling it requires expansion of every upstream link as well.",
    since: "2020-12-31",
    kind: "treaty",
    confidence: "documented",
    source: "TAP AG throughput reporting; ENTSOG",
    sourceUrl: "https://www.tap-ag.com/",
    lastVerified: "2026-09-20",
  },
  {
    id: "igb",
    name: "Greece–Bulgaria Interconnector (IGB)",
    short: "IGB",
    product: "gas",
    status: "operating",
    operator: "ICGB AD",
    operatorState: "BGR",
    transit: ["GRC", "BGR"],
    capacity: { value: 3, unit: "bcm/yr" },
    path: [
      [41.12, 25.4],
      [41.3, 25.5],
      [41.6, 25.4],
      [41.9, 25.5],
      [42.2, 25.6],
      [42.43, 25.64],
    ],
    statusNote:
      "Small, and the single most consequential piece of gas infrastructure built in the Balkans since 2022: it is what let Bulgaria survive Gazprom's April 2022 supply cut by taking Azerbaijani and LNG-sourced gas from Greece instead. A 3 bcm line changed a national outcome.",
    since: "2022-10-01",
    kind: "treaty",
    confidence: "documented",
    source: "ICGB AD commissioning record; ENTSOG",
    sourceUrl: "https://www.icgb.eu/",
    lastVerified: "2026-09-20",
  },
  {
    id: "baltic-pipe",
    name: "Baltic Pipe",
    short: "Baltic Pipe",
    product: "gas",
    status: "operating",
    operator: "Energinet / GAZ-SYSTEM",
    operatorState: "POL",
    transit: ["NOR", "DNK", "POL"],
    capacity: { value: 10, unit: "bcm/yr" },
    path: [
      [56.0, 3.5],
      [55.9, 5.0],
      [55.8, 7.0],
      [55.65, 8.55],
      [55.5, 10.0],
      [55.4, 11.5],
      [55.2, 12.3],
      [54.8, 13.5],
      [54.3, 14.5],
      [54.1, 15.06],
      [53.8, 14.9],
      [53.55, 14.83],
    ],
    statusNote:
      "Opened for commercial flow on 30 November 2022, seven months after Russia cut Poland off, and sized at 10 bcm against the roughly 9 bcm Poland used to take via Yamal. The timing was coincidence — it had been in planning since 2001 — but the substitution was close to exact, which is why Poland could refuse rouble payment without rationing.",
    since: "2022-11-30",
    kind: "treaty",
    confidence: "documented",
    source: "GAZ-SYSTEM and Energinet commissioning records",
    sourceUrl: "https://www.baltic-pipe.eu/",
    lastVerified: "2026-09-20",
    zone: "ukraine",
  },
  {
    id: "transmed",
    name: "Trans-Mediterranean (Enrico Mattei)",
    short: "Transmed",
    product: "gas",
    status: "operating",
    operator: "Sonatrach / Eni",
    operatorState: "DZA",
    transit: ["DZA", "TUN", "ITA"],
    capacity: { value: 33.5, unit: "bcm/yr" },
    path: [
      [32.9, 3.3],
      [33.5, 5.5],
      [34.2, 7.5],
      [34.8, 9.0],
      [35.5, 10.5],
      [36.4, 10.8],
      [37.0, 11.5],
      [37.4, 12.1],
      [37.65, 12.6],
    ],
    statusNote:
      "Algeria overtook Russia as Italy's largest gas supplier in 2022 largely through this line, and Eni has signed successive uplift deals on it since. The constraint is Algerian upstream decline and rising domestic demand rather than pipe capacity, which is why announced volume increases keep outrunning delivered ones.",
    since: "1983-06-01",
    kind: "treaty",
    confidence: "documented",
    source: "Eni and Sonatrach supply agreements; ENTSOG entry data",
    sourceUrl: "https://transparency.entsog.eu/",
    lastVerified: "2026-09-20",
  },
  {
    id: "medgaz",
    name: "Medgaz",
    short: "Medgaz",
    product: "gas",
    status: "operating",
    operator: "Medgaz S.A. (Sonatrach/Naturgy)",
    operatorState: "DZA",
    transit: ["DZA", "ESP"],
    capacity: { value: 10.5, unit: "bcm/yr" },
    path: [
      [35.3, -1.38],
      [35.7, -1.6],
      [36.1, -1.9],
      [36.5, -2.2],
      [36.83, -2.45],
    ],
    statusNote:
      "Algeria's direct subsea route to Spain, expanded to 10.5 bcm at the end of 2021 — immediately before Algeria closed the overland route through Morocco. The two events together moved Spain from two Algerian pipelines to one, and made Spanish LNG regasification the swing supply for the western Mediterranean.",
    since: "2011-04-01",
    kind: "treaty",
    confidence: "documented",
    source: "Medgaz S.A. and Enagás capacity filings",
    sourceUrl: "https://www.medgaz.com/",
    lastVerified: "2026-09-20",
  },
  {
    id: "gme",
    name: "Maghreb–Europe Gas Pipeline (GME)",
    short: "GME",
    product: "gas",
    status: "suspended",
    operator: "Sonatrach / Metragaz",
    operatorState: "DZA",
    transit: ["DZA", "MAR", "ESP"],
    capacity: { value: 13.5, unit: "bcm/yr" },
    path: [
      [32.9, 3.3],
      [33.6, 1.5],
      [34.2, -0.5],
      [34.6, -2.0],
      [34.8, -3.5],
      [35.2, -5.0],
      [35.55, -5.5],
      [36.0, -5.6],
      [36.7, -5.4],
      [37.5, -5.0],
      [37.88, -4.78],
    ],
    statusNote:
      "Shut by Algeria on 31 October 2021 when it refused to renew the transit contract over Morocco's normalisation with Israel and the Western Sahara dispute — no great power, no sanctions regime, one bilateral quarrel. Since 2022 it has run backwards at low volume, Spain to Morocco, on regasified LNG.",
    since: "2021-10-31",
    kind: "state-action",
    confidence: "documented",
    source: "Algerian Ministry of Energy statement; Enagás flow data",
    sourceUrl: "https://www.enagas.es/en/",
    lastVerified: "2026-09-20",
  },
  {
    id: "keystone",
    name: "Keystone (Hardisty–Patoka–Cushing)",
    short: "Keystone",
    product: "crude",
    status: "operating",
    operator: "South Bow",
    operatorState: "CAN",
    transit: ["CAN", "USA"],
    capacity: { value: 0.62, unit: "mmbd" },
    path: [
      [52.67, -111.3],
      [51.5, -108.5],
      [50.4, -105.5],
      [49.5, -102.0],
      [48.6, -99.5],
      [47.0, -98.0],
      [45.5, -97.2],
      [43.5, -97.3],
      [41.5, -97.0],
      [40.03, -97.0],
      [39.5, -95.5],
      [38.5, -95.7],
      [36.5, -96.2],
      [35.98, -96.77],
    ],
    statusNote:
      "The line that was built, as distinct from Keystone XL, whose presidential permit was revoked in January 2021 and which was cancelled outright that June. It has had repeated large spills — 14,000 barrels in Kansas in December 2022 — and a pressure restriction imposed by US regulators as a result, so its effective capacity sits below nameplate.",
    since: "2010-06-30",
    kind: "state-action",
    confidence: "documented",
    source: "PHMSA enforcement record; South Bow operational notices",
    sourceUrl: "https://www.phmsa.dot.gov/",
    lastVerified: "2026-09-20",
  },
];
