/**
 * Curated regime-level framing that no live feed states.
 *
 * Phase 2's caution drives the split in this file: designation rosters change far
 * faster than anything a curated list can track, so no names appear here. What
 * appears is the framing — the number the oil price cap is set at, which US
 * executive orders cover energy, and which programmes are comprehensive rather
 * than sectoral. The EU's own regime list arrives live from the Sanctions Map API
 * and is not duplicated here; only the non-EU regimes and the cap are.
 *
 * `lastVerified` is on every entry because these ARE curated and will go stale.
 */
import type { SanctionsRegime } from "./sanctions.ts";

const US_URL = "https://ofac.treasury.gov/sanctions-programs-and-country-information";

export const CURATED_REGIMES: SanctionsRegime[] = [
  {
    id: "g7-price-cap-crude",
    name: "G7 / EU / UK price cap on seaborne Russian crude",
    short: "Price cap (crude)",
    authority: "G7",
    measureClass: "price-cap",
    targets: ["RUS"],
    energy: true,
    sectors: ["Crude oil", "Maritime transport", "Insurance", "Brokering"],
    instrument: "EU Reg. 833/2014 Art. 3n as amended; UK OFSI Oil Price Cap guidance; US OFAC determination of 5 Dec 2022",
    instrumentUrl: "https://eur-lex.europa.eu/eli/reg/2014/833/oj",
    since: "2022-12-05",
    note: "A ceiling, not a ban, and that distinction is the whole design: G7-domiciled shipping, insurance and brokering may carry Russian crude only if it sold at or below the cap, most recently lowered to $47.60 a barrel with a floating mechanism. Its measurable effect has been to push cargoes onto a shadow fleet outside G7 insurance rather than to stop them, which is why the designated-vessel list on this board is the instrument that actually bites.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "g7-price-cap-products",
    name: "G7 / EU / UK price cap on seaborne Russian refined products",
    short: "Price cap (products)",
    authority: "G7",
    measureClass: "price-cap",
    targets: ["RUS"],
    energy: true,
    sectors: ["Refined petroleum products", "Maritime transport", "Insurance"],
    instrument: "EU Reg. 833/2014 Art. 3n; Price Cap Coalition determination of 5 Feb 2023",
    instrumentUrl: "https://eur-lex.europa.eu/eli/reg/2014/833/oj",
    since: "2023-02-05",
    note: "Two ceilings rather than one — a higher cap for premium products such as diesel and a lower one for discounted products such as fuel oil. Refining Russian crude in a third country and selling the output onward was the principal gap until the EU's refined-products import rule closed part of it in 2026.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "us-russia-eo14024",
    name: "US blocking sanctions on Russia (EO 14024 / 14065 / 14071)",
    short: "US Russia",
    authority: "US",
    measureClass: "broad-sectoral",
    targets: ["RUS"],
    energy: true,
    sectors: ["Financial services", "Energy", "Shipping", "Technology", "Defence industry"],
    instrument: "Executive Orders 14024, 14065, 14071; CAATSA Title II",
    instrumentUrl: US_URL,
    since: "2021-04-15",
    note: "RUSSIA-EO14024 is the single largest programme tag on the SDN list by a wide margin. It is a designation authority rather than an embargo: nothing prohibits US persons from dealing with Russia as such, only with the thousands of named banks, shipping companies and vessels — plus, since the 2024 secondary-sanctions expansion, any foreign bank that does.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "us-iran",
    name: "US comprehensive sanctions on Iran",
    short: "US Iran",
    authority: "US",
    measureClass: "comprehensive",
    targets: ["IRN"],
    energy: true,
    sectors: ["Petroleum", "Petrochemicals", "Shipping", "Banking", "Insurance", "Metals"],
    instrument: "Iranian Transactions and Sanctions Regulations 31 CFR 560; EOs 13846, 13902, 13876",
    instrumentUrl: US_URL,
    since: "1995-05-06",
    note: "The nearest thing on this map to a genuine comprehensive embargo: a general prohibition on US persons dealing with Iran at all, layered with secondary sanctions that reach non-US buyers of Iranian crude. Iranian exports have nonetheless run at well over a million barrels a day, almost entirely to China via ship-to-ship transfers, which is the measure of how far designation diverges from interdiction.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "us-venezuela",
    name: "US sanctions on Venezuela (EO 13850 / 13884)",
    short: "US Venezuela",
    authority: "US",
    measureClass: "sectoral",
    targets: ["VEN"],
    energy: true,
    sectors: ["Petroleum", "Gold", "Government of Venezuela"],
    instrument: "Executive Orders 13850, 13884; General Licence 44 and successors",
    instrumentUrl: US_URL,
    since: "2018-11-01",
    note: "The one energy programme on this board that has been eased and re-tightened repeatedly by general licence rather than by amending the order, so the legal text is a poor guide to what is permitted this quarter. PdVSA is blocked; specific liftings by named majors are licensed.",
    kind: "state-action",
    confidence: "reported",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "us-dprk",
    name: "US comprehensive sanctions on North Korea",
    short: "US DPRK",
    authority: "US",
    measureClass: "comprehensive",
    targets: ["PRK"],
    energy: true,
    sectors: ["All trade", "Shipping", "Refined petroleum", "Banking", "Labour exports"],
    instrument: "North Korea Sanctions Regulations 31 CFR 510; EOs 13466–13810",
    instrumentUrl: US_URL,
    since: "2008-06-26",
    note: "Comprehensive in law and porous in practice: the UN refined-petroleum import cap of 500,000 barrels a year is exceeded openly, and the Panel of Experts that reported on it was ended by a Russian veto in 2024, so there is no longer an official monitor. The 122 DPRK-designated ships under UNSCR 1718 are the traceable part.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "un-1718-dprk",
    name: "UN Security Council measures on North Korea (UNSCR 1718 and successors)",
    short: "UN DPRK",
    authority: "UN",
    measureClass: "broad-sectoral",
    targets: ["PRK"],
    energy: true,
    sectors: ["Arms", "Refined petroleum", "Crude oil", "Coal", "Seafood", "Shipping", "Labour"],
    instrument: "UNSCR 1718 (2006), 2270, 2321, 2371, 2375, 2397",
    instrumentUrl: "https://www.un.org/securitycouncil/sanctions/1718",
    since: "2006-10-14",
    note: "Binding on every UN member, which makes it the only regime here that China and Russia are formally obliged to enforce. Both have blocked further designations since 2022 and the monitoring Panel of Experts was terminated in April 2024, so the list is frozen rather than current.",
    kind: "treaty",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "gb-russia-oil",
    name: "UK sanctions on Russian oil, shipping and the shadow fleet",
    short: "UK Russia",
    authority: "GB",
    measureClass: "broad-sectoral",
    targets: ["RUS"],
    energy: true,
    sectors: ["Oil", "Oil products", "Shipping", "Insurance", "Financial services"],
    instrument: "Russia (Sanctions) (EU Exit) Regulations 2019 as amended",
    instrumentUrl: "https://www.gov.uk/government/collections/uk-sanctions-on-russia",
    since: "2019-04-10",
    note: "Disproportionately important for its size because London writes most of the world's marine insurance: a UK shipping or insurance prohibition removes cover from a tanker anywhere on earth. The UK has specified several hundred vessels by IMO number, which is why a designated-ship list is the operative instrument rather than a country shading.",
    kind: "state-action",
    confidence: "documented",
    live: false,
    lastVerified: "2026-09-20",
  },
  {
    id: "us-syria-legacy",
    name: "US sanctions on Syria (post-2024 restructuring)",
    short: "US Syria",
    authority: "US",
    measureClass: "designated-entities",
    targets: ["SYR"],
    energy: true,
    sectors: ["Petroleum", "Named persons and entities"],
    instrument: "Syrian Sanctions Regulations 31 CFR 542; Caesar Act as waived",
    instrumentUrl: US_URL,
    since: "2011-04-29",
    note: "Listed at the weakest class deliberately: after the fall of the Assad government the general Syria embargo was progressively replaced by general licences and named designations, and this board will not render Syria as comprehensively embargoed on the strength of a statute whose operative parts are waived. Treat as reported.",
    kind: "state-action",
    confidence: "reported",
    live: false,
    lastVerified: "2026-09-20",
  },
];

/**
 * Every ISO3 any curated regime names, plus the states the EU Sanctions Map has
 * regimes for. The country-outline reducer unions this with the alliance roster,
 * because Zimbabwe and Myanmar have no alliance on this board and would otherwise
 * have no polygon to paint.
 */
export const SANCTIONED_COUNTRIES = [
  "AFG",
  "BDI",
  "BIH",
  "BLR",
  "CAF",
  "CHN",
  "COD",
  "GIN",
  "GNB",
  "GTM",
  "HTI",
  "IRN",
  "IRQ",
  "LBN",
  "LBY",
  "MDA",
  "MLI",
  "MMR",
  "MNE",
  "NER",
  "NIC",
  "PRK",
  "RUS",
  "SDN",
  "SOM",
  "SRB",
  "SSD",
  "SYR",
  "TUN",
  "TUR",
  "UKR",
  "USA",
  "VEN",
  "YEM",
  "ZWE",
] as const;
